-- €

-- --------------------------------------------
--  DefaultATNConfig.swift
--  antlr.swift

with Foundation;
--public struct DefaultATNConfig: ATNConfig {
--    public state: ATNState
--    public alt : Integer;
--    public context: Optional_PredictionContext;
--    public semanticContext: SemanticContext
--    public hashValue: Integer {
-- --------------------------------------------
--        hashCode: Integer := 7
--        hashCode := 31 * hashCode + state.stateNumber
--        hashCode := 31 * hashCode + alt
--        hashCode := 31 * hashCode + semanticContext.hashValue
--        return hashCode
-- --------------------------------------------
--    }
-- --------------------------------------------
-- --------------------------------------------
--}
-- --------------------------------------------
--public function ==(lhs: DefaultATNConfig, rhs: DefaultATNConfig) return Boolean is
begin
-- --------------------------------------------
--    if lhs === rhs then
--        return True;
--    }
-- --------------------------------------------
--    same : constant : Boolean =
--    lhs.state.stateNumber = rhs.state.stateNumber and
--            lhs.alt = rhs.alt and
--            lhs.semanticContext = rhs.semanticContext
-- --------------------------------------------
--    return same
-- --------------------------------------------
--}
--public type DefaultATNConfig is new ATNConfig with null record;
{
-- --------------------------------------------
--    override
--    public hashValue: Integer {
-- --------------------------------------------
--        hashCode: Integer := 7
--        hashCode := 31 * hashCode + state.stateNumber
--        hashCode := 31 * hashCode + alt
--        hashCode := 31 * hashCode + semanticContext.hashValue
--        return hashCode
-- --------------------------------------------
--    }
-- --------------------------------------------
-- --------------------------------------------
--}
-- --------------------------------------------
--public function ==(lhs: DefaultATNConfig, rhs: DefaultATNConfig) return Boolean is
begin
-- --------------------------------------------
--    if lhs === rhs then
--        return True;
--    }
-- --------------------------------------------
--    same : constant : Boolean =
--    lhs.state.stateNumber = rhs.state.stateNumber and
--            lhs.alt = rhs.alt and
--            lhs.semanticContext = rhs.semanticContext
-- --------------------------------------------
--    return same
-- --------------------------------------------
--}
