-- €

with Ada.Containers.Vectors;
with Ada.Finalization;
with Ada.Wide_Wide_Characters.Handling;
with ANTLR.Runtime.Token_Protocol;

use Ada.Wide_Wide_Characters.Handling;
use ANTLR.Runtime;
use ANTLR.Runtime.Token_Protocol;

package ANTLR.Runtime.Vocabularies is

   --
   -- This class provides a default implementation of the _org.antlr.v4.runtime.Vocabulary_
   -- interface.
   --

   package Names_Container is new Ada.Containers.Vectors (
      Index_Type => Natural,
      Item_Type => UString,
      "=" => "=");
   subtype Names_List is Names_Container.Vector;

   -- private static
   EMPTY_NAMES : constant Vocabulary := Names_Container.To_Vector (New_Item => "", Length => 1);

   -- public
   type Vocabulary is new Ada.Finalization.Controlled with private; -- and Hashable

   subtype Object is Vocabulary;
   type Class is access all Object;
   type Class_Wide is access all Object'Class;

   -- public
   function "=" (Lhs, Rhs : Vocabulary) return Boolean
      is (lhs.literalNames = rhs.literalNames
      and  lhs.symbolicName = rhs.symbolicName
      and  lhs.displayNames = rhs.displayNames);

   -- public
   procedure hash (This : Vocabulary; hasher : in out Hasher);

   --
   -- Gets an empty _org.antlr.v4.runtime.Vocabulary_ instance.
   --
   --
   -- No literal or symbol names are assigned to token types, so
   -- _#getDisplayName (int)_ returns the numeric value for all tokens
   -- except _org.antlr.v4.runtime.Token#EOF_.
   --
   -- public static
   EMPTY_VOCABULARY : constant Vocabulary := (EMPTY_NAMES, EMPTY_NAMES, EMPTY_NAMES);

   --
   -- Constructs a new instance of _org.antlr.v4.runtime.Vocabulary_ from the specified
   -- literal and symbolic token names.
   --
   -- * SeeAlso: #getLiteralName (int);
   -- * SeeAlso: #getSymbolicName (int);
   -- * Parameter literalNames: The literal names assigned to tokens, or `null`
   -- if no literal names are assigned.
   -- * Parameter symbolicNames: The symbolic names assigned to tokens, or
   -- `null` if no symbolic names are assigned.
   --
   --
   -- public convenience
   procedure Initialize (Self : in out Vocabulary;
                         literalNames : Optional_UString_List;
                         symbolicNames : Optional_UString_List);

   --
   -- Constructs a new instance of _org.antlr.v4.runtime.Vocabulary_ from the specified
   -- literal, symbolic, and display token names.
   --
   -- * SeeAlso: #getLiteralName (int);
   -- * SeeAlso: #getSymbolicName (int);
   -- * SeeAlso: #getDisplayName (int);
   -- * Parameter literalNames: The literal names assigned to tokens, or `null`
   --   if no literal names are assigned.
   -- * Parameter symbolicNames: The symbolic names assigned to tokens, or
   --   `null` if no symbolic names are assigned.
   -- * Parameter displayNames: The display names assigned to tokens, or `null`
   --   to use the values in `literalNames` and `symbolicNames` as
   --   the source of display names, as described in
   --   _#getDisplayName (int)_.
   --
   --
   -- public
   procedure Initialize (Self : in out Vocabulary;
                         literalNames  : Optional_UString_List := Vocabulary.EMPTY_NAMES;
                         symbolicNames : Optional_UString_List := Vocabulary.EMPTY_NAMES;
                         displayNames  : Optional_UString_List := Vocabulary.EMPTY_NAMES);

   --
   -- Returns a _org.antlr.v4.runtime.Vocabulary_ instance from the specified set of token
   -- names. This method acts as a compatibility layer for the single
   -- `tokenNames` array generated by previous releases of ANTLR.
   --
   -- The resulting vocabulary instance returns `null` for
   -- _#getLiteralName (int)_ and _#getSymbolicName (int)_, and the
   -- value from `tokenNames` for the display names.
   --
   -- * Parameter tokenNames: The token names, or `null` if no token names are
   -- available.
   -- * Returns: A _org.antlr.v4.runtime.Vocabulary_ instance which uses `tokenNames` for
   -- the display names of tokens.
   --
   -- public static
   function fromTokenNames (tokenNames : Optional_UString_List) return Vocabulary;

   -- public
   function getLiteralName (This : Vocabulary; tokenType : Token_Kind) return Optional_UString;

   -- public
   function getSymbolicName (This : Vocabulary; tokenType : Token_Kind) return Optional_UString;

   -- public
   function getDisplayName (This : Vocabulary; tokenType : Token_Kind) return UString;

private
   type Vocabulary is new Ada.Finalization.Controlled with -- and Hashable
   record
      -- private
      literalNames : Name_Container; -- constant
      -- private
      symbolicNames : Name_Container; -- constant
      -- private
      displayNames : Name_Container; -- constant
   end record;

end ANTLR.Runtime.Vocabularies;
