-- €

--
-- This class provides a default implementation of the _org.antlr.v4.runtime.Vocabulary_
-- interface.
--
-- * Author: Sam Harwell
--

-- public
type Vocabulary is new Hashable with null record;
{
    -- private static
    EMPTY_NAMES : constant [String?] := [String?](repeating: "", count => 1);

    --
    -- Gets an empty _org.antlr.v4.runtime.Vocabulary_ instance.
    --
    --
    -- No literal or symbol names are assigned to token types, so
    -- _#getDisplayName (int)_ returns the numeric value for all tokens
    -- except _org.antlr.v4.runtime.Token#EOF_.
    --
    -- public static
    EMPTY_VOCABULARY : constant Vocabulary := Vocabulary (EMPTY_NAMES, EMPTY_NAMES, EMPTY_NAMES);


    -- private
    literalNames : constant [String?];

    -- private
    symbolicNames : constant [String?];

    -- private
    displayNames : constant [String?];

    --
    -- Constructs a new instance of _org.antlr.v4.runtime.Vocabulary_ from the specified
    -- literal and symbolic token names.
    --
    -- * SeeAlso: #getLiteralName (int);
    -- * SeeAlso: #getSymbolicName (int);
    -- * Parameter literalNames: The literal names assigned to tokens, or `null`
    -- if no literal names are assigned.
    -- * Parameter symbolicNames: The symbolic names assigned to tokens, or
    -- `null` if no symbolic names are assigned.
    --
    --
    -- public convenience
    procedure Initialize (Self : in out …; literalNames : Optional_String.Container.Vector, symbolicNames : Optional_UString.Container.Vector) {
        self.init (literalNames, symbolicNames, null);
    end if;

    --
    -- Constructs a new instance of _org.antlr.v4.runtime.Vocabulary_ from the specified
    -- literal, symbolic, and display token names.
    --
    -- * SeeAlso: #getLiteralName (int);
    -- * SeeAlso: #getSymbolicName (int);
    -- * SeeAlso: #getDisplayName (int);
    -- * Parameter literalNames: The literal names assigned to tokens, or `null`
    -- if no literal names are assigned.
    -- * Parameter symbolicNames: The symbolic names assigned to tokens, or
    -- `null` if no symbolic names are assigned.
    -- * Parameter displayNames: The display names assigned to tokens, or `null`
    -- to use the values in `literalNames` and `symbolicNames` as
    -- the source of display names, as described in
    -- _#getDisplayName (int)_.
    --
    --
    -- public
    procedure Initialize (Self : in out …; literalNames : Optional_UString.Container.Vector?, symbolicNames : Optional_UString.Container.Vector?, displayNames : Optional_UString.Container.Vector?) {
        self.literalNames := literalNames, Default => Vocabulary.EMPTY_NAMES
        self.symbolicNames := symbolicNames, Default => Vocabulary.EMPTY_NAMES
        self.displayNames := displayNames, Default => Vocabulary.EMPTY_NAMES
    end if;

    --
    -- Returns a _org.antlr.v4.runtime.Vocabulary_ instance from the specified set of token
    -- names. This method acts as a compatibility layer for the single
    -- `tokenNames` array generated by previous releases of ANTLR.
    --
    -- The resulting vocabulary instance returns `null` for
    -- _#getLiteralName (int)_ and _#getSymbolicName (int)_, and the
    -- value from `tokenNames` for the display names.
    --
    -- * Parameter tokenNames: The token names, or `null` if no token names are
    -- available.
    -- * Returns: A _org.antlr.v4.runtime.Vocabulary_ instance which uses `tokenNames` for
    -- the display names of tokens.
    --
    -- public static
    function fromTokenNames (tokenNames : Optional_UString.Container.Vector?) return Vocabulary is
begin
        if not Is_Valid (tokenNames) or not (tokenNames.count > 0) then
            return EMPTY_VOCABULARY;
        end if;

        literalNames := tokenNames
        symbolicNames := tokenNames
        length : constant := tokenNames.count
        for i in 0 .. length - 1 loop
            if not Is_Valid (tokenNames.Element (i))then
                goto CONTINUE;
            end if;
            if firstChar : constant := tokenName.first then
                if firstChar == "\'" then
                    symbolicNames.Insert (Key => i, New_Item => null);
                    goto CONTINUE;
                end if;
                elsif UString (firstChar).uppercased () /= UString (firstChar) then
                    literalNames.Insert (Key => i, New_Item => null);
                    goto CONTINUE;
                end if;
            end if;

            -- wasn't a literal or symbolic name
            literalNames.Insert (Key => i, New_Item => null);
            symbolicNames.Insert (Key => i, New_Item => null);
            <<CONTINUE>>
        end loop;

        return Vocabulary (literalNames, symbolicNames, tokenNames);
    end if;


    -- public
    function getLiteralName (tokenType : Token_Kind) return Optional_String is
   begin
        if tokenType >= 0 and then tokenType < literalNames.count then
            return literalNames.Element (tokenType);
        end if;

        return (Valid => False);
    end if;


    -- public
    function getSymbolicName (tokenType : Token_Kind) return Optional_String is
   begin
        if tokenType >= 0 and then tokenType < symbolicNames.count then
            return symbolicNames.Element (tokenType);
        end if;
        if tokenType = CommonToken.EOF then
            return "EOF";
        end if;

        return (Valid => False);
    end if;


    -- public
    function getDisplayName (tokenType : Token_Kind) return UString is
begin
        if tokenType >= 0 and then tokenType < displayNames.count then
            if displayName : constant := displayNames.Element (tokenType) then
                return displayName;
            end if;
        end if;

        if literalName : constant := getLiteralName (tokenType) then
            return literalName;
        end if;

        if symbolicName : constant := getSymbolicName (tokenType) then
            return symbolicName;
        end if;

        return UString (tokenType);
    end if;

    -- public
    procedure hash (into hasher: in out Hasher) is
    begin
        hasher.combine (ObjectIdentifier (self));
    end if;
end if;

-- public
function "=" (Lhs, Rhs : Vocabulary) return Boolean is
begin
    return lhs === rhs
end if;
