with Ada.Text_IO;
use Ada.Text_IO;

with Aspect;
with Aspect.Advices;
with Option;
with ANTLR;
with ANTLR.Runtime;
with ANTLR.Runtime.ATN;
with ANTLR.Runtime.ATN.States.BlockStartStates.BasicBlockStartStates;
with ANTLR.Runtime.ATN.States.BasicStates;
with ANTLR.Runtime.ATN.CommonUtil;
with ANTLR.Runtime.ATN.Configs;
with ANTLR.Runtime.ATN.Configs.LexerConfigs;
with ANTLR.Runtime.ATN.ConfigSets;
with ANTLR.Runtime.ATN.DecisionEventInfos;
with ANTLR.Runtime.ATN.DecisionEventInfos.AmbiguityInfos;
with ANTLR.Runtime.ATN.DecisionEventInfos.ContextSensitivityInfos;
with ANTLR.Runtime.ATN.DecisionEventInfos.ErrorInfos;
with ANTLR.Runtime.ATN.DecisionEventInfos.LookaheadEventInfos;
with ANTLR.Runtime.ATN.DecisionEventInfos.PredicateEvalInfos;
with ANTLR.Runtime.ATN.DecisionInfos;
with ANTLR.Runtime.ATN.DefaultATNConfig;
with ANTLR.Runtime.ATN.DeserializationOptions;
with ANTLR.Runtime.ATN.Deserializers;
with ANTLR.Runtime.ATN.LexerActionExecutors;
with ANTLR.Runtime.ATN.LexerActions;
with ANTLR.Runtime.ATN.LexerActions.LexerChannelActions;
with ANTLR.Runtime.ATN.LexerActions.LexerCustomActions;
with ANTLR.Runtime.ATN.LexerActions.LexerIndexedCustomActions;
with ANTLR.Runtime.ATN.LexerActions.LexerModeActions;
with ANTLR.Runtime.ATN.LexerActions.LexerMoreActions;
with ANTLR.Runtime.ATN.LexerActions.LexerPopModeActions;
with ANTLR.Runtime.ATN.LexerActions.LexerPushModeActions;
with ANTLR.Runtime.ATN.LexerActions.LexerSkipActions;
with ANTLR.Runtime.ATN.LexerActions.LexerTypeActions;
with ANTLR.Runtime.ATN.LexerActionTypes;
with ANTLR.Runtime.ATN.LL1Analyzer;
with ANTLR.Runtime.ATN.LookupConfigs;
with ANTLR.Runtime.ATN.ParseInfos;
with ANTLR.Runtime.ATN.PredictionContextCache;
with ANTLR.Runtime.ATN.PredictionContexts;
with ANTLR.Runtime.ATN.PredictionContexts.ArrayPredictionContexts;
with ANTLR.Runtime.ATN.PredictionContexts.SingletonPredictionContexts.EmptyPredictionContexts;
with ANTLR.Runtime.ATN.PredictionModes;
with ANTLR.Runtime.ATN.SemanticContexts;
with ANTLR.Runtime.ATN.Simulators;
with ANTLR.Runtime.ATN.Simulators.LexerSimulators;
with ANTLR.Runtime.ATN.SingletonPredictionContext;
with ANTLR.Runtime.ATN.States;
with ANTLR.Runtime.ATN.States.BlockEndStates;
with ANTLR.Runtime.ATN.States.DecisionStates;
with ANTLR.Runtime.ATN.States.DecisionStates.BlockStartStates;
with ANTLR.Runtime.ATN.States.DecisionStates.BlockStartStates.PlusBlockStartStates;
with ANTLR.Runtime.ATN.States.DecisionStates.BlockStartStates.StarBlockStartStates;
with ANTLR.Runtime.ATN.States.DecisionStates.PlusLoopbackStates;
with ANTLR.Runtime.ATN.States.DecisionStates.StarLoopEntryStates;
with ANTLR.Runtime.ATN.States.DecisionStates.TokensStartStates;
with ANTLR.Runtime.ATN.States.LoopEndStates;
with ANTLR.Runtime.ATN.States.RuleStartStates;
with ANTLR.Runtime.ATN.States.RuleStopStates;
with ANTLR.Runtime.ATN.States.StarLoopbackStates;
with ANTLR.Runtime.ATN.Transitions;
with ANTLR.Runtime.ATN.Transitions.AbstractPredicateTransitions;
with ANTLR.Runtime.ATN.Transitions.AbstractPredicateTransitions.PrecedencePredicateTransitions;
with ANTLR.Runtime.ATN.Transitions.AbstractPredicateTransitions.PredicateTransitions;
with ANTLR.Runtime.ATN.Transitions.ActionTransitions;
with ANTLR.Runtime.ATN.Transitions.AtomTransitions;
with ANTLR.Runtime.ATN.Transitions.EpsilonTransitions;
with ANTLR.Runtime.ATN.Transitions.RangeTransitions;
with ANTLR.Runtime.ATN.Transitions.RuleTransitions;
with ANTLR.Runtime.ATN.Transitions.SetTransitions;
with ANTLR.Runtime.ATN.Transitions.SetTransitions.NotSetTransitions;
with ANTLR.Runtime.ATN.Transitions.WildcardTransitions;
with ANTLR.Runtime.DFA.Serializers;
with ANTLR.Runtime.DFA.Serializers.LexerSerializers;
with ANTLR.Runtime.DFA.States;
with ANTLR.Runtime.LookupDictionary;
with ANTLR.Runtime.Misc;
with ANTLR.Runtime.Misc.BitSets;
with ANTLR.Runtime.Misc.DoubleKeyMap;
with ANTLR.Runtime.Misc.Intervals;
with ANTLR.Runtime.Misc.Utils.Mutex;
with ANTLR.Runtime.RecognitionExceptions.LexerNoViableAltExceptions;
with ANTLR.Runtime.Recognizer_Protocol;
with ANTLR.Runtime.Recognizers;
with ANTLR.Runtime.Recognizers.Lexers;
with ANTLR.Runtime.Recognizers.Lexers.Interpreters;
with ANTLR.Runtime.Recognizers.Parsers;
with ANTLR.Runtime.RuleContexts.ParserRuleContexts;
with ANTLR.Runtime.RuleContexts.ParserRuleContexts.InterpreterRuleContexts;
with ANTLR.Runtime.Token_Protocol;
with ANTLR.Runtime.TokenStreamRewriters;
with ANTLR.Runtime.TokenFactories.CommonTokenFactories;
with ANTLR.Runtime.Tree_Protocol;
with ANTLR.Runtime.Tree.ParseTree_Protocol;
with ANTLR.Runtime.Tree.ParseTreeListener_Protocol;
with ANTLR.Runtime.Tree.ParseTreeVisitors;
with ANTLR.Runtime.Tree.ParseTreeVisitors.AbstractParseTreeVisitors;
with ANTLR.Runtime.Tree.ParseTreeWalkers;
with ANTLR.Runtime.Tree.RuleNode_Protocol;
with ANTLR.Runtime.Tree.SyntaxTree_Protocol;
with ANTLR.Runtime.Tree.TerminalNode_Protocol;
with ANTLR.Runtime.WritableTokens.CommonTokens;
with ANTLR.Runtime.Misc.Exceptions.Errors;
with ANTLR.Runtime.Misc.Exceptions;

procedure Main is

   type Color is (Blue, Green, Red);
   for Color use (
      Blue => Character'Pos ('B'),
      Green => Character'Pos ('G'),
      Red  => Character'Pos ('R'));
   for Color'Size use 8;

   package Option_Color is new Option (Color);
   subtype Optional_Color is Option_Color.Optional; -- renames

   use Option_Color;

   My_Color : Optional_Color;

begin
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (My_Color, Red)");
   --  Set (My_Color, Red);
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (My_Color, ""Red"")");
   --  Value (My_Color, "Red");
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (My_Color, ""YELLOW"")");
   --  Value (My_Color, "YELLOW");
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (My_Color, " & Color'Pos (Color'Last)'Image & ")");
   --  Val (My_Color, Color'Pos (Color'Last));
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");
   --  Put_Line ("Set (My_Color, " & Character'Pos ('R')'Image & ")");
   --  Enum_Val (My_Color, Character'Pos ('R'));
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");

   Put_Line ("===============");
   Put_Line ("Set (Red)");
   --  set (Red);
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (""Red"")");
   --  Value ("Red");
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (""YELLOW"")");
   --  Value ("YELLOW");
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");
   --  Put_Line ("Set (" & Color'Pos (Color'Last)'Image & ")");
   --  Val (Color'Pos (Color'Last));
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");
   --  Put_Line ("Set (" & Character'Pos ('R')'Image & ")");
   --  Enum_Val (Character'Pos ('R'));
   --  Put_Line (My_Color'Image);
   Put_Line ("===============");

   Aspect.Is_Active (Aspect.DEBUG) := False;
   Aspect.Is_Active (Aspect.TRACE) := False;
   Aspect.Is_Active (Aspect.PROFILING_TIME) := True;

end Main;
