with Ada.Text_IO;
use Ada.Text_IO;

with Option;
with ANTLR;
with ANTLR.Runtime;
with ANTLR.Runtime.Misc;
-- with ANTLR.Runtime.Misc.ANTLRException;
-- with ANTLR.Runtime.Misc.BitSet;
-- with ANTLR.Runtime.Misc.DoubleKeyMap;
-- with ANTLR.Runtime.Misc.InterpreterDataReader;
with ANTLR.Runtime.Misc.Interval;
with ANTLR.Runtime.Misc.IntervalSet;
with ANTLR.Runtime.Misc.IntSet;
-- with ANTLR.Runtime.Misc.MultiMap;
-- with ANTLR.Runtime.Misc.MurmurHash;
-- with ANTLR.Runtime.Misc.Extensions.ArrayExtension;
-- with ANTLR.Runtime.Misc.Extensions.CharacterExtension;
-- with ANTLR.Runtime.Misc.Extensions.IntStreamExtension;
-- with ANTLR.Runtime.Misc.Extensions.StringExtension;
-- with ANTLR.Runtime.Misc.Extensions.TokenExtension;
-- with ANTLR.Runtime.Misc.Extensions.UUIDExtension;
-- with ANTLR.Runtime.Misc.Utils.CommonUtil;
-- with ANTLR.Runtime.Misc.Utils.Mutex;
-- with ANTLR.Runtime.Misc.Utils.Stack;
-- with ANTLR.Runtime.Misc.Utils;
with ANTLR.Runtime.ANTLRError;
-- with ANTLR.Runtime.ANTLRErrorListener;
-- with ANTLR.Runtime.ANTLRErrorStrategy;
-- with ANTLR.Runtime.ANTLRFileStream;
-- with ANTLR.Runtime.ANTLRInputStream;
-- with ANTLR.Runtime.BailErrorStrategy;
-- with ANTLR.Runtime.BaseErrorListener;
-- with ANTLR.Runtime.BufferedTokenStream;
-- with ANTLR.Runtime.CharStream;
-- with ANTLR.Runtime.CommonToken;
-- with ANTLR.Runtime.CommonTokenFactory;
-- with ANTLR.Runtime.CommonTokenStream;
-- with ANTLR.Runtime.ConsoleErrorListener;
-- with ANTLR.Runtime.DefaultErrorStrategy;
-- with ANTLR.Runtime.DiagnosticErrorListener;
-- with ANTLR.Runtime.FailedPredicateException;
-- with ANTLR.Runtime.InputMismatchException;
-- with ANTLR.Runtime.InterpreterRuleContext;
-- with ANTLR.Runtime.IntStream;
-- with ANTLR.Runtime.Lexer;
-- with ANTLR.Runtime.LexerInterpreter;
-- with ANTLR.Runtime.LexerNoViableAltException;
-- with ANTLR.Runtime.ListTokenSource;
-- with ANTLR.Runtime.NoViableAltException;
-- with ANTLR.Runtime.Parser;
-- with ANTLR.Runtime.ParserInterpreter;
-- with ANTLR.Runtime.ParserRuleContext;
-- with ANTLR.Runtime.ProxyErrorListener;
-- with ANTLR.Runtime.RecognitionException;
-- with ANTLR.Runtime.Recognizer;
-- with ANTLR.Runtime.RuleContext;
-- with ANTLR.Runtime.RuntimeMetaData;
-- with ANTLR.Runtime.Token;
-- with ANTLR.Runtime.TokenFactory;
-- with ANTLR.Runtime.TokenSource;
-- with ANTLR.Runtime.TokenStream;
-- with ANTLR.Runtime.TokenStreamRewriter;
-- with ANTLR.Runtime.UnbufferedCharStream;
-- with ANTLR.Runtime.UnbufferedTokenStream;
-- with ANTLR.Runtime.VocabularySingle;
-- with ANTLR.Runtime.WritableToken;
-- with ANTLR.Runtime.ATN;
-- with ANTLR.Runtime.ATN.AbstractPredicateTransition;
-- with ANTLR.Runtime.ATN.ActionTransition;
-- with ANTLR.Runtime.ATN.AmbiguityInfo;
-- with ANTLR.Runtime.ATN.ArrayPredictionContext;
-- with ANTLR.Runtime.ATN.ATNConfig;
-- with ANTLR.Runtime.ATN.ATNConfigSet;
-- with ANTLR.Runtime.ATN.ATNDeserializationOptions;
-- with ANTLR.Runtime.ATN.ATNDeserializer;
-- with ANTLR.Runtime.ATN.ATNSimulator;
with ANTLR.Runtime.ATN.ATNStates;
-- with ANTLR.Runtime.ATN.ATNType;
-- with ANTLR.Runtime.ATN.AtomTransition;
-- with ANTLR.Runtime.ATN.BasicBlockStartState;
-- with ANTLR.Runtime.ATN.BasicState;
-- with ANTLR.Runtime.ATN.BlockEndState;
-- with ANTLR.Runtime.ATN.BlockStartState;
-- with ANTLR.Runtime.ATN.CommonUtil;
-- with ANTLR.Runtime.ATN.ContextSensitivityInfo;
-- with ANTLR.Runtime.ATN.DecisionEventInfo;
-- with ANTLR.Runtime.ATN.DecisionInfo;
-- with ANTLR.Runtime.ATN.DecisionState;
-- with ANTLR.Runtime.ATN.DefaultATNConfig;
-- with ANTLR.Runtime.ATN.EmptyPredictionContext;
-- with ANTLR.Runtime.ATN.EpsilonTransition;
-- with ANTLR.Runtime.ATN.ErrorInfo;
with ANTLR.Runtime.ATN.LexerAction;
-- with ANTLR.Runtime.ATN.LexerActionExecutor;
-- with ANTLR.Runtime.ATN.LexerActionType;
-- with ANTLR.Runtime.ATN.LexerATNConfig;
-- with ANTLR.Runtime.ATN.LexerATNSimulator;
-- with ANTLR.Runtime.ATN.LexerChannelAction;
-- with ANTLR.Runtime.ATN.LexerCustomAction;
-- with ANTLR.Runtime.ATN.LexerIndexedCustomAction;
-- with ANTLR.Runtime.ATN.LexerModeAction;
-- with ANTLR.Runtime.ATN.LexerPopModeAction;
-- with ANTLR.Runtime.ATN.LexerPushModeAction;
-- with ANTLR.Runtime.ATN.LexerSkipAction;
-- with ANTLR.Runtime.ATN.LexerTypeAction;
-- with ANTLR.Runtime.ATN.LL1Analyzer;
-- with ANTLR.Runtime.ATN.LookaheadEventInfo;
-- with ANTLR.Runtime.ATN.LookupATNConfig;
-- with ANTLR.Runtime.ATN.LookupDictionary;
-- with ANTLR.Runtime.ATN.LoopEndState;
-- with ANTLR.Runtime.ATN.NotSetTransition;
-- with ANTLR.Runtime.ATN.ParseInfo;
-- with ANTLR.Runtime.ATN.ParserATNSimulator;
-- with ANTLR.Runtime.ATN.PlusBlockStartState;
-- with ANTLR.Runtime.ATN.PlusLoopbackState;
-- with ANTLR.Runtime.ATN.PrecedencePredicateTransition;
-- with ANTLR.Runtime.ATN.PredicateEvalInfo;
-- with ANTLR.Runtime.ATN.PredicateTransition;
-- with ANTLR.Runtime.ATN.PredictionContext;
-- with ANTLR.Runtime.ATN.PredictionContextCache;
-- with ANTLR.Runtime.ATN.PredictionMode;
-- with ANTLR.Runtime.ATN.ProfilingATNSimulator;
-- with ANTLR.Runtime.ATN.RangeTransition;
-- with ANTLR.Runtime.ATN.RuleStartState;
-- with ANTLR.Runtime.ATN.RuleStopState;
-- with ANTLR.Runtime.ATN.RuleTransition;
-- with ANTLR.Runtime.ATN.SemanticContext;
-- with ANTLR.Runtime.ATN.SetTransition;
-- with ANTLR.Runtime.ATN.SingletonPredictionContext;
-- with ANTLR.Runtime.ATN.StarBlockStartState;
-- with ANTLR.Runtime.ATN.StarLoopbackState;
-- with ANTLR.Runtime.ATN.StarLoopEntryState;
-- with ANTLR.Runtime.ATN.TokensStartState;
with ANTLR.Runtime.ATN.Transitions;
-- with ANTLR.Runtime.ATN.WildcardTransition;
-- with ANTLR.Runtime.DFA;
-- with ANTLR.Runtime.DFA.DFASerializer;
-- with ANTLR.Runtime.DFA.DFAState;
-- with ANTLR.Runtime.DFA.LexerDFASerializer;
-- with ANTLR.Runtime.Tree;
-- with ANTLR.Runtime.Tree.AbstractParseTreeVisitor;
-- with ANTLR.Runtime.Tree.ErrorNode;
-- with ANTLR.Runtime.Tree.ParseTree;
-- with ANTLR.Runtime.Tree.ParseTreeListener;
-- with ANTLR.Runtime.Tree.ParseTreeProperty;
-- with ANTLR.Runtime.Tree.ParseTreeVisitor;
-- with ANTLR.Runtime.Tree.ParseTreeWalker;
-- with ANTLR.Runtime.Tree.RuleNode;
-- with ANTLR.Runtime.Tree.SyntaxTree;
-- with ANTLR.Runtime.Tree.TerminalNode;
-- with ANTLR.Runtime.Tree.TerminalNodeImpl;
-- with ANTLR.Runtime.Tree.Trees;
-- with ANTLR.Runtime.Tree.Pattern.Chunk;
-- with ANTLR.Runtime.Tree.Pattern.ParseTreeMatch;
-- with ANTLR.Runtime.Tree.Pattern.ParseTreePattern;
-- with ANTLR.Runtime.Tree.Pattern.ParseTreePatternMatcher;
-- with ANTLR.Runtime.Tree.Pattern.RuleTagToken;
-- with ANTLR.Runtime.Tree.Pattern.TagChunk;
-- with ANTLR.Runtime.Tree.Pattern.TextChunk;
-- with ANTLR.Runtime.Tree.Pattern.TokenTagToken;

procedure Main is

   type Color is (Blue, Green, Red);
   for Color use (
      Blue => Character'Pos ('B'),
      Green => Character'Pos ('G'),
      Red  => Character'Pos ('R'));
   for Color'Size use 8;

   package Optional_Color is new Option (Color);
   use Optional_Color;

   My_Color : Optional_Color.Optional;

begin
   Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (My_Color, Red)");
   Set (My_Color, Red);
   Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (My_Color, ""Red"")");
   Value (My_Color, "Red");
   Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (My_Color, ""YELLOW"")");
   Value (My_Color, "YELLOW");
   Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (My_Color, " & Color'Pos (Color'Last)'Image & ")");
   Val (My_Color, Color'Pos (Color'Last));
   Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (My_Color, " & Character'Pos ('R')'Image & ")");
   Enum_Val (My_Color, Character'Pos ('R'));
   Put_Line (My_Color'Image);
   Put_Line ("===============");

   Put_Line ("===============");
   Put_Line ("Set (Red)");
   Set (Red);
   Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (""Red"")");
   Value ("Red");
   Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (""YELLOW"")");
   Value ("YELLOW");
   Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (" & Color'Pos (Color'Last)'Image & ")");
   Val (Color'Pos (Color'Last));
   Put_Line (My_Color'Image);
   Put_Line ("===============");
   Put_Line ("Set (" & Character'Pos ('R')'Image & ")");
   Enum_Val (Character'Pos ('R'));
   Put_Line (My_Color'Image);
   Put_Line ("===============");
end Main;
