-- Copyright (c) 2012-2017 The ANTLR Project. All rights reserved.
-- Use of this file is governed by the BSD 3-clause license that
-- can be found in the LICENSE.txt file in the project root.
--


-- 
-- This class provides a default implementation of the _org.antlr.v4.runtime.Vocabulary_
-- interface.
-- 
-- - Author: Sam Harwell
-- 

-- public
type Vocabulary is new Hashable with null record;
{
    -- private static
    EMPTY_NAMES : constant [String?] := [String?](repeating: "", count: 1);

    -- 
    -- Gets an empty _org.antlr.v4.runtime.Vocabulary_ instance.
    -- 
    -- 
    -- No literal or symbol names are assigned to token types, so
    -- _#getDisplayName(int)_ returns the numeric value for all tokens
    -- except _org.antlr.v4.runtime.Token#EOF_.
    -- 
    -- public static 
    EMPTY_VOCABULARY : constant Vocabulary := Vocabulary(EMPTY_NAMES, EMPTY_NAMES, EMPTY_NAMES);


    -- private 
    literalNames : constant [String?];

    -- private 
    symbolicNames : constant [String?];

    -- private 
    displayNames : constant [String?];

    -- 
    -- Constructs a new instance of _org.antlr.v4.runtime.Vocabulary_ from the specified
    -- literal and symbolic token names.
    -- 
    -- - SeeAlso: #getLiteralName(int)
    -- - SeeAlso: #getSymbolicName(int)
    -- - Parameter literalNames: The literal names assigned to tokens, or `null`
    -- if no literal names are assigned.
    -- - Parameter symbolicNames: The symbolic names assigned to tokens, or
    -- `null` if no symbolic names are assigned.
    -- 
    -- 
    -- public convenience
    procedure Init (Self : in out …; literalNames : [String?], symbolicNames : [String?]) {
        self.init(literalNames, symbolicNames, null)
    end if;

    -- 
    -- Constructs a new instance of _org.antlr.v4.runtime.Vocabulary_ from the specified
    -- literal, symbolic, and display token names.
    -- 
    -- - SeeAlso: #getLiteralName(int)
    -- - SeeAlso: #getSymbolicName(int)
    -- - SeeAlso: #getDisplayName(int)
    -- - Parameter literalNames: The literal names assigned to tokens, or `null`
    -- if no literal names are assigned.
    -- - Parameter symbolicNames: The symbolic names assigned to tokens, or
    -- `null` if no symbolic names are assigned.
    -- - Parameter displayNames: The display names assigned to tokens, or `null`
    -- to use the values in `literalNames` and `symbolicNames` as
    -- the source of display names, as described in
    -- _#getDisplayName(int)_.
    -- 
    -- 
    -- public 
    procedure Init (Self : in out …; literalNames : [String?]?, symbolicNames : [String?]?, displayNames : [String?]?) {
        self.literalNames := literalNames ?? Vocabulary.EMPTY_NAMES
        self.symbolicNames := symbolicNames ?? Vocabulary.EMPTY_NAMES
        self.displayNames := displayNames ?? Vocabulary.EMPTY_NAMES
    end if;

    -- 
    -- Returns a _org.antlr.v4.runtime.Vocabulary_ instance from the specified set of token
    -- names. This method acts as a compatibility layer for the single
    -- `tokenNames` array generated by previous releases of ANTLR.
    -- 
    -- The resulting vocabulary instance returns `null` for
    -- _#getLiteralName(int)_ and _#getSymbolicName(int)_, and the
    -- value from `tokenNames` for the display names.
    -- 
    -- - Parameter tokenNames: The token names, or `null` if no token names are
    -- available.
    -- - Returns: A _org.antlr.v4.runtime.Vocabulary_ instance which uses `tokenNames` for
    -- the display names of tokens.
    -- 
    -- public static
    function fromTokenNames (tokenNames : [String?]?) return Vocabulary is
begin
        if not Is_Valid (tokenNames) or not (tokenNames.count > 0) then
            return EMPTY_VOCABULARY;
        end if;

        var literalNames := tokenNames
        var symbolicNames := tokenNames
        length : constant := tokenNames.count
        for i in 0 .. length - 1 loop
            guard tokenName : constant := tokenNames[i] else {
                continue
            end if;
            if firstChar : constant := tokenName.first then
                if firstChar == "\'" then
                    symbolicNames[i] := null;
                    continue
                end if;
                elsif String(firstChar).uppercased() /= String(firstChar) then
                    literalNames[i] := null;
                    continue
                end if;
            end if;

            -- wasn't a literal or symbolic name
            literalNames[i] := null;
            symbolicNames[i] := null;
        end loop;

        return Vocabulary(literalNames, symbolicNames, tokenNames)
    end if;


    -- public
    function getLiteralName (tokenType : Integer) return Optional_String is
   begin
        if tokenType >= 0 and then tokenType < literalNames.count then
            return literalNames[tokenType];
        end if;

        return null;
    end if;


    -- public
    function getSymbolicName (tokenType : Integer) return Optional_String is
   begin
        if tokenType >= 0 and then tokenType < symbolicNames.count then
            return symbolicNames[tokenType];
        end if;
        if tokenType = CommonToken.EOF then
            return "EOF";
        end if;

        return null;
    end if;


    -- public
    function getDisplayName (tokenType : Integer) return String is
begin
        if tokenType >= 0 and then tokenType < displayNames.count then
            if displayName : constant := displayNames[tokenType] then
                return displayName;
            end if;
        end if;

        if literalName : constant := getLiteralName(tokenType) then
            return literalName;
        end if;

        if symbolicName : constant := getSymbolicName(tokenType) then
            return symbolicName;
        end if;

        return String(tokenType)
    end if;

    -- public
    procedure hash (into hasher: inout Hasher) is
    begin
        hasher.combine(ObjectIdentifier(self))
    end if;
end if;

-- public
function "=" (lhs: Vocabulary, rhs: Vocabulary) return Boolean is
begin
    return lhs === rhs
end if;
