-- 
-- Copyright (c) 2012-2017 The ANTLR Project. All rights reserved.
-- Use of this file is governed by the BSD 3-clause license that
-- can be found in the LICENSE.txt file in the project root.
-- 

--
--  DefaultATNConfig.swift
--  antlr.swift
--
--  Created by janyou on 15/9/14.
--

with Foundation;
--public struct DefaultATNConfig: ATNConfig {
--    public var state: ATNState
--    public var alt : Integer;
--    public var context: PredictionContext?
--    public var semanticContext: SemanticContext
--    public var hashValue: Integer {
--
--        var hashCode: Integer := 7
--        hashCode := 31 * hashCode + state.stateNumber
--        hashCode := 31 * hashCode + alt
--        hashCode := 31 * hashCode + semanticContext.hashValue
--        return hashCode
--
--    end ;
--
--
--end ;
--
--public function ==(lhs: DefaultATNConfig, rhs: DefaultATNConfig) return Boolean is
begin
--
--    if lhs === rhs then
--        return true
--    end ;
--
--    same : constant : Boolean =
--    lhs.state.stateNumber == rhs.state.stateNumber and
--            lhs.alt == rhs.alt and
--            lhs.semanticContext == rhs.semanticContext
--
--    return same
--
--end ;
--public type DefaultATNConfig is new ATNConfig with null record;
{
--
--    override
--    public var hashValue: Integer {
--
--        var hashCode: Integer := 7
--        hashCode := 31 * hashCode + state.stateNumber
--        hashCode := 31 * hashCode + alt
--        hashCode := 31 * hashCode + semanticContext.hashValue
--        return hashCode
--
--    end ;
--
--
--end ;
--
--public function ==(lhs: DefaultATNConfig, rhs: DefaultATNConfig) return Boolean is
begin
--
--    if lhs === rhs then
--        return true
--    end ;
--
--    same : constant : Boolean =
--    lhs.state.stateNumber == rhs.state.stateNumber and
--            lhs.alt == rhs.alt and
--            lhs.semanticContext == rhs.semanticContext
--
--    return same
--
--end ;
