#!/bin/ksh
# mv -v "src/atn/ANTLR-Runtime-ATN-AbstractPredicateTransition.adb "src/atn/ANTLR-Runtime-ATN-AbstractPredicateTransition.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-AbstractPredicateTransition.ads "src/atn/ANTLR-Runtime-ATN-AbstractPredicateTransition.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ActionTransition.adb "src/atn/ANTLR-Runtime-ATN-ActionTransition.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-AmbiguityInfo.adb "src/atn/ANTLR-Runtime-ATN-AmbiguityInfo.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ArrayPredictionContext.adb "src/atn/ANTLR-Runtime-ATN-ArrayPredictionContext.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ATNConfig.adb "src/atn/ANTLR-Runtime-ATN-ATNConfig.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ATNConfigSet.adb "src/atn/ANTLR-Runtime-ATN-ATNConfigSet.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ATNDeserializationOptions.ads "src/atn/ANTLR-Runtime-ATN-ATNDeserializationOptions.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ATNDeserializer.adb "src/atn/ANTLR-Runtime-ATN-ATNDeserializer.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ATNSimulator.adb "src/atn/ANTLR-Runtime-ATN-ATNSimulator.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ATNStates.adb "src/atn/ANTLR-Runtime-ATN-ATNStates.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ATNStates.ads "src/atn/ANTLR-Runtime-ATN-ATNStates.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-ATNType.ads "src/atn/ANTLR-Runtime-ATN-ATNType.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-LexerActionType.ads "src/atn/ANTLR-Runtime-ATN-LexerActionType.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-LookupDictionary.ads "src/atn/ANTLR-Runtime-ATN-LookupDictionary.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN-PredictionContext.adb "src/atn/ANTLR-Runtime-ATN-PredictionContext.adb"
# mv -v "src/atn/ANTLR-Runtime-ATN.ads "src/atn/ANTLR-Runtime-ATN.adb"
# mv -v "src/misc/ANTLR-Runtime-Misc-Interval.ads "src/misc/ANTLR-Runtime-Misc-Interval.adb"
# mv -v "tests/src/TokenStreamRewriterTests.adb "tests/src/TokenStreamRewriterTests.adb"
# mv -v "tests/src/TokenStreamTests.adb "tests/src/TokenStreamTests.adb"
# mv -v "tests/src/VisitorTests.adb "tests/src/VisitorTests.adb"
cp -v "src/misc/ANTLR-Runtime-Misc.ads" "src/misc/extensions/ANTLR-Runtime-Misc-Extensions.ads"
mv -v "src/ANTLRErrorListener.swift.ada" "src/ANTLR-Runtime-ANTLRErrorListener.adb"
mv -v "src/ANTLRErrorStrategy.swift.ada" "src/ANTLR-Runtime-ANTLRErrorStrategy.adb"
mv -v "src/ANTLRFileStream.swift.ada" "src/ANTLR-Runtime-ANTLRFileStream.adb"
mv -v "src/ANTLRInputStream.swift.ada" "src/ANTLR-Runtime-ANTLRInputStream.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-AtomTransition.swift.ada" "src/atn/ANTLR-Runtime-ATN-AtomTransition.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-BasicBlockStartState.swift.ada" "src/atn/ANTLR-Runtime-ATN-BasicBlockStartState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-BasicState.swift.ada" "src/atn/ANTLR-Runtime-ATN-BasicState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-BlockEndState.swift.ada" "src/atn/ANTLR-Runtime-ATN-BlockEndState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-BlockStartState.swift.ada" "src/atn/ANTLR-Runtime-ATN-BlockStartState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-CommonUtil.ada" "src/atn/ANTLR-Runtime-ATN-CommonUtil.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-ContextSensitivityInfo.swift.ada" "src/atn/ANTLR-Runtime-ATN-ContextSensitivityInfo.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-DecisionEventInfo.swift.ada" "src/atn/ANTLR-Runtime-ATN-DecisionEventInfo.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-DecisionInfo.swift.ada" "src/atn/ANTLR-Runtime-ATN-DecisionInfo.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-DecisionState.swift.ada" "src/atn/ANTLR-Runtime-ATN-DecisionState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-DefaultATNConfig.swift.ada" "src/atn/ANTLR-Runtime-ATN-DefaultATNConfig.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-EmptyPredictionContext.swift.ada" "src/atn/ANTLR-Runtime-ATN-EmptyPredictionContext.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-EpsilonTransition.swift.ada" "src/atn/ANTLR-Runtime-ATN-EpsilonTransition.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-ErrorInfo.swift.ada" "src/atn/ANTLR-Runtime-ATN-ErrorInfo.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerActionExecutor.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerActionExecutor.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerATNConfig.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerATNConfig.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerATNSimulator.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerATNSimulator.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerChannelAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerChannelAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerCustomAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerCustomAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerIndexedCustomAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerIndexedCustomAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerModeAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerModeAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerMoreAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerMoreAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerPopModeAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerPopModeAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerPushModeAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerPushModeAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerSkipAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerSkipAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LexerTypeAction.swift.ada" "src/atn/ANTLR-Runtime-ATN-LexerTypeAction.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LL1Analyzer.swift.ada" "src/atn/ANTLR-Runtime-ATN-LL1Analyzer.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LookaheadEventInfo.swift.ada" "src/atn/ANTLR-Runtime-ATN-LookaheadEventInfo.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LookupATNConfig.swift.ada" "src/atn/ANTLR-Runtime-ATN-LookupATNConfig.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-LoopEndState.ada" "src/atn/ANTLR-Runtime-ATN-LoopEndState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-NotSetTransition.ada" "src/atn/ANTLR-Runtime-ATN-NotSetTransition.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-ParseInfo.ada" "src/atn/ANTLR-Runtime-ATN-ParseInfo.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-ParserATNSimulator.ada" "src/atn/ANTLR-Runtime-ATN-ParserATNSimulator.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-PlusBlockStartState.ada" "src/atn/ANTLR-Runtime-ATN-PlusBlockStartState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-PlusLoopbackState.ada" "src/atn/ANTLR-Runtime-ATN-PlusLoopbackState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-PrecedencePredicateTransition.ada" "src/atn/ANTLR-Runtime-ATN-PrecedencePredicateTransition.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-PredicateEvalInfo.ada" "src/atn/ANTLR-Runtime-ATN-PredicateEvalInfo.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-PredicateTransition.ada" "src/atn/ANTLR-Runtime-ATN-PredicateTransition.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-PredictionContextCache.ada" "src/atn/ANTLR-Runtime-ATN-PredictionContextCache.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-PredictionMode.ada" "src/atn/ANTLR-Runtime-ATN-PredictionMode.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-ProfilingATNSimulator.ada" "src/atn/ANTLR-Runtime-ATN-ProfilingATNSimulator.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-RangeTransition.ada" "src/atn/ANTLR-Runtime-ATN-RangeTransition.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-RuleStartState.ada" "src/atn/ANTLR-Runtime-ATN-RuleStartState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-RuleStopState.ada" "src/atn/ANTLR-Runtime-ATN-RuleStopState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-RuleTransition.ada" "src/atn/ANTLR-Runtime-ATN-RuleTransition.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-SemanticContext.ada" "src/atn/ANTLR-Runtime-ATN-SemanticContext.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-SetTransition.ada" "src/atn/ANTLR-Runtime-ATN-SetTransition.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-SingletonPredictionContext.ada" "src/atn/ANTLR-Runtime-ATN-SingletonPredictionContext.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-StarBlockStartState.ada" "src/atn/ANTLR-Runtime-ATN-StarBlockStartState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-StarLoopbackState.swift.ada" "src/atn/ANTLR-Runtime-ATN-StarLoopbackState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-StarLoopEntryState.swift.ada" "src/atn/ANTLR-Runtime-ATN-StarLoopEntryState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-TokensStartState.swift.ada" "src/atn/ANTLR-Runtime-ATN-TokensStartState.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-Transition.swift.ada" "src/atn/ANTLR-Runtime-ATN-Transition.adb"
mv -v "src/atn/ANTLR-Runtime-ATN-WildcardTransition.swift.ada" "src/atn/ANTLR-Runtime-ATN-WildcardTransition.adb"
mv -v "src/BailErrorStrategy.swift.ada" "src/ANTLR-Runtime-BailErrorStrategy.adb"
mv -v "src/BaseErrorListener.swift.ada" "src/ANTLR-Runtime-BaseErrorListener.adb"
mv -v "src/BufferedTokenStream.swift.ada" "src/ANTLR-Runtime-BufferedTokenStream.adb"
mv -v "src/CharStream.swift.ada" "src/ANTLR-Runtime-CharStream.adb"
mv -v "src/CommonToken.swift.ada" "src/CommonToken.adb"
mv -v "src/CommonTokenFactory.swift.ada" "src/ANTLR-Runtime-CommonTokenFactory.adb"
mv -v "src/CommonTokenStream.swift.ada" "src/ANTLR-Runtime-CommonTokenStream.adb"
mv -v "src/ConsoleErrorListener.swift.ada" "src/ANTLR-Runtime-ConsoleErrorListener.adb"
mv -v "src/DefaultErrorStrategy.swift.ada" "src/ANTLR-Runtime-DefaultErrorStrategy.adb"
mv -v "src/dfa/DFA.ada" "src/dfa/ANTLR-Runtime-DFA.adb"
mv -v "src/dfa/DFASerializer.ada" "src/dfa/ANTLR-Runtime-DFA-DFASerializer.adb"
mv -v "src/dfa/DFAState.ada" "src/dfa/ANTLR-Runtime-DFA-DFAState.adb"
mv -v "src/dfa/LexerDFASerializer.ada" "src/dfa/ANTLR-Runtime-DFA-LexerDFASerializer.adb"
mv -v "src/DiagnosticErrorListener.swift.ada" "src/DiagnosticErrorListener.adb"
mv -v "src/FailedPredicateException.swift.ada" "src/ANTLR-Runtime-FailedPredicateException.adb"
mv -v "src/InputMismatchException.swift.ada" "src/ANTLR-Runtime-InputMismatchException.adb"
mv -v "src/InterpreterRuleContext.swift.ada" "src/InterpreterRuleContext.adb"
mv -v "src/IntStream.swift.ada" "src/ANTLR-Runtime-IntStream.adb"
mv -v "src/Lexer.swift.ada" "src/ANTLR-Runtime-Lexer.adb"
mv -v "src/LexerInterpreter.swift.ada" "src/ANTLR-Runtime-LexerInterpreter.adb"
mv -v "src/LexerNoViableAltException.swift.ada" "src/ANTLR-Runtime-LexerNoViableAltException.adb"
mv -v "src/ListTokenSource.swift.ada" "src/ANTLR-Runtime-ListTokenSource.adb"
mv -v "src/misc/ANTLR-Runtime-Misc-IntervalSet.ada" "src/misc/ANTLR-Runtime-Misc-IntervalSet.adb"
mv -v "src/misc/BitSet.ada" "src/misc/ANTLR-Runtime-Misc-BitSet.adb"
mv -v "src/misc/DoubleKeyMap.ada" "src/misc/ANTLR-Runtime-Misc-DoubleKeyMap.adb"
mv -v "src/misc/exception/ANTLRException.ada" "src/misc/exception/ANTLR-Runtime-Misc-ANTLRException.adb"
mv -v "src/misc/extension/ArrayExtension.ada" "src/misc/extension/ANTLR-Runtime-Misc-Extensions-ArrayExtension.adb"
mv -v "src/misc/extension/CharacterExtension.ada" "src/misc/extension/ANTLR-Runtime-Misc-Extensions-CharacterExtension.adb"
mv -v "src/misc/extension/IntStreamExtension.ada" "src/misc/extension/ANTLR-Runtime-Misc-Extensions-IntStreamExtension.adb"
mv -v "src/misc/extension/StringExtension.ada" "src/misc/extension/ANTLR-Runtime-Misc-Extensions-StringExtension.adb"
mv -v "src/misc/extension/TokenExtension.ada" "src/misc/extension/ANTLR-Runtime-Misc-Extensions-TokenExtension.adb"
mv -v "src/misc/extension/UUIDExtension.ada" "src/misc/extension/ANTLR-Runtime-Misc-Extensions-UUIDExtension.adb"
mv -v "src/misc/InterpreterDataReader.ada" "src/misc/ANTLR-Runtime-Misc-InterpreterDataReader.adb"
mv -v "src/misc/IntSet.ada" "src/misc/ANTLR-Runtime-Misc-IntSet.adb"
mv -v "src/misc/MultiMap.ada" "src/misc/ANTLR-Runtime-Misc-MultiMap.adb"
mv -v "src/misc/MurmurHash.ada" "src/misc/ANTLR-Runtime-Misc-MurmurHash.adb"
mv -v "src/misc/Utils.ada" "src/misc/utils/ANTLR-Runtime-Misc-Utils.adb"
mv -v "src/misc/utils/CommonUtil.ada" "src/misc/utils/ANTLR-Runtime-Misc-Utils-CommonUtil.adb"
mv -v "src/misc/utils/Mutex.ada" "src/misc/utils/ANTLR-Runtime-Misc-Utils-Mutex.adb"
mv -v "src/misc/utils/Stack.ada" "src/misc/utils/ANTLR-Runtime-Misc-Utils-Stack.adb"
mv -v "src/NoViableAltException.swift.ada" "src/ANTLR-Runtime-NoViableAltException.adb"
mv -v "src/Parser.swift.ada" "src/ANTLR-Runtime-Parser.adb"
mv -v "src/ParserInterpreter.swift.ada" "src/ParserInterpreter.adb"
mv -v "src/ParserRuleContext.swift.ada" "src/ANTLR-Runtime-ParserRuleContext.adb"
mv -v "src/ProxyErrorListener.swift.ada" "src/ANTLR-Runtime-ProxyErrorListener.adb"
mv -v "src/RecognitionException.swift.ada" "src/ANTLR-Runtime-RecognitionException.adb"
mv -v "src/Recognizer.swift.ada" "src/ANTLR-Runtime-Recognizer.adb"
mv -v "src/RuleContext.swift.ada" "src/ANTLR-Runtime-RuleContext.adb"
mv -v "src/RuntimeMetaData.swift.ada" "src/ANTLR-Runtime-RuntimeMetaData.adb"
mv -v "src/Token.swift.ada" "src/ANTLR-Runtime-Token.adb"
mv -v "src/TokenFactory.swift.ada" "src/ANTLR-Runtime-TokenFactory.adb"
mv -v "src/TokenSource.swift.ada" "src/ANTLR-Runtime-TokenSource.adb"
mv -v "src/TokenStream.swift.ada" "src/ANTLR-Runtime-TokenStream.adb"
mv -v "src/TokenStreamRewriter.swift.ada" "src/ANTLR-Runtime-TokenStreamRewriter.adb"
mv -v "src/tree/AbstractParseTreeVisitor.swift.ada" "src/tree/ANTLR-Runtime-Tree-AbstractParseTreeVisitor.adb"
mv -v "src/tree/ErrorNode.swift.ada" "src/tree/ANTLR-Runtime-Tree-ErrorNode.adb"
mv -v "src/tree/ParseTree.swift.ada" "src/tree/ANTLR-Runtime-Tree-ParseTree.adb"
mv -v "src/tree/ParseTreeListener.swift.ada" "src/tree/ANTLR-Runtime-Tree-ParseTreeListener.adb"
mv -v "src/tree/ParseTreeProperty.swift.ada" "src/tree/ANTLR-Runtime-Tree-ParseTreeProperty.adb"
mv -v "src/tree/ParseTreeVisitor.swift.ada" "src/tree/ANTLR-Runtime-Tree-ParseTreeVisitor.adb"
mv -v "src/tree/ParseTreeWalker.swift.ada" "src/tree/ANTLR-Runtime-Tree-ParseTreeWalker.adb"
mv -v "src/tree/pattern/Chunk.ada" "src/tree/pattern/ANTLR-Runtime-Tree-Pattern-Chunk.adb"
mv -v "src/tree/pattern/ParseTreeMatch.ada" "src/tree/pattern/ANTLR-Runtime-Tree-Pattern-ParseTreeMatch.adb"
mv -v "src/tree/pattern/ParseTreePattern.ada" "src/tree/pattern/ANTLR-Runtime-Tree-Pattern-ParseTreePattern.adb"
mv -v "src/tree/pattern/ParseTreePatternMatcher.ada" "src/tree/pattern/ANTLR-Runtime-Tree-Pattern-ParseTreePatternMatcher.adb"
mv -v "src/tree/pattern/RuleTagToken.ada" "src/tree/pattern/ANTLR-Runtime-Tree-Pattern-RuleTagToken.adb"
mv -v "src/tree/pattern/TagChunk.ada" "src/tree/pattern/ANTLR-Runtime-Tree-Pattern-TagChunk.adb"
mv -v "src/tree/pattern/TextChunk.ada" "src/tree/pattern/ANTLR-Runtime-Tree-Pattern-TextChunk.adb"
mv -v "src/tree/pattern/TokenTagToken.ada" "src/tree/pattern/ANTLR-Runtime-Tree-Pattern-TokenTagToken.adb"
mv -v "src/tree/RuleNode.swift.ada" "src/tree/ANTLR-Runtime-Tree-RuleNode.adb"
mv -v "src/tree/SyntaxTree.swift.ada" "src/tree/ANTLR-Runtime-Tree-SyntaxTree.adb"
mv -v "src/tree/TerminalNode.swift.ada" "src/tree/ANTLR-Runtime-Tree-TerminalNode.adb"
mv -v "src/tree/TerminalNodeImpl.swift.ada" "src/tree/ANTLR-Runtime-Tree-TerminalNodeImpl.adb"
mv -v "src/tree/Tree.swift.ada" "src/tree/ANTLR-Runtime-Tree.adb"
mv -v "src/tree/Trees.swift.ada" "src/tree/ANTLR-Runtime-Tree-Trees.adb"
mv -v "src/UnbufferedCharStream.swift.ada" "src/ANTLR-Runtime-UnbufferedCharStream.adb"
mv -v "src/UnbufferedTokenStream.swift.ada" "src/ANTLR-Runtime-UnbufferedTokenStream.adb"
mv -v "src/VocabularySingle.swift.ada" "src/ANTLR-Runtime-VocabularySingle.adb"
mv -v "src/WritableToken.swift.ada" "src/ANTLR-Runtime-WritableToken.adb"
mv -v "tests/LinuxMain.swift.ada" "tests/LinuxMain.adb"
mv -v "tests/src/ANTLRInputStreamTests.swift.ada" "tests/src/ANTLRInputStreamTests.adb"
mv -v "tests/src/InterpreterDataTests.swift.ada" "tests/src/InterpreterDataTests.adb"
mv -v "tests/src/MurmurHashTests.swift.ada" "tests/src/MurmurHashTests.adb"
mv -v "tests/src/ParseTreePatternMatcherTests.swift.ada" "tests/src/ParseTreePatternMatcherTests.adb"
mv -v "tests/src/RuntimeMetaDataTests.swift.ada" "tests/src/RuntimeMetaDataTests.adb"
mv -v "tests/src/StringExtensionTests.swift.ada" "tests/src/StringExtensionTests.adb"
mv -v "tests/src/ThreadingTests.swift.ada" "tests/src/ThreadingTests.adb"
