-- Copyright (c) 2012-2017 The ANTLR Project. All rights reserved.
-- Use of this file is governed by the BSD 3-clause license that
-- can be found in the LICENSE.txt file in the project root.
--


-- 
-- This class provides a default implementation of the _org.antlr.v4.runtime.Vocabulary_
-- interface.
-- 
-- - Author: Sam Harwell
-- 

public type Vocabulary is new Hashable with null record;
{
    private static let EMPTY_NAMES: [String?] := [String?](repeating: "", count: 1)

    -- 
    -- Gets an empty _org.antlr.v4.runtime.Vocabulary_ instance.
    -- 
    -- 
    -- No literal or symbol names are assigned to token types, so
    -- _#getDisplayName(int)_ returns the numeric value for all tokens
    -- except _org.antlr.v4.runtime.Token#EOF_.
    -- 
    public static let EMPTY_VOCABULARY: Vocabulary := Vocabulary(EMPTY_NAMES, EMPTY_NAMES, EMPTY_NAMES)


    private let literalNames: [String?]

    private let symbolicNames: [String?]

    private let displayNames: [String?]

    -- 
    -- Constructs a new instance of _org.antlr.v4.runtime.Vocabulary_ from the specified
    -- literal and symbolic token names.
    -- 
    -- - SeeAlso: #getLiteralName(int)
    -- - SeeAlso: #getSymbolicName(int)
    -- - Parameter literalNames: The literal names assigned to tokens, or `null`
    -- if no literal names are assigned.
    -- - Parameter symbolicNames: The symbolic names assigned to tokens, or
    -- `null` if no symbolic names are assigned.
    -- 
    -- 
    public convenience init(literalNames : [String?], symbolicNames : [String?]) {
        self.init(literalNames, symbolicNames, null)
    end ;

    -- 
    -- Constructs a new instance of _org.antlr.v4.runtime.Vocabulary_ from the specified
    -- literal, symbolic, and display token names.
    -- 
    -- - SeeAlso: #getLiteralName(int)
    -- - SeeAlso: #getSymbolicName(int)
    -- - SeeAlso: #getDisplayName(int)
    -- - Parameter literalNames: The literal names assigned to tokens, or `null`
    -- if no literal names are assigned.
    -- - Parameter symbolicNames: The symbolic names assigned to tokens, or
    -- `null` if no symbolic names are assigned.
    -- - Parameter displayNames: The display names assigned to tokens, or `null`
    -- to use the values in `literalNames` and `symbolicNames` as
    -- the source of display names, as described in
    -- _#getDisplayName(int)_.
    -- 
    -- 
    public init(literalNames : [String?]?, symbolicNames : [String?]?, displayNames : [String?]?) {
        self.literalNames := literalNames ?? Vocabulary.EMPTY_NAMES
        self.symbolicNames := symbolicNames ?? Vocabulary.EMPTY_NAMES
        self.displayNames := displayNames ?? Vocabulary.EMPTY_NAMES
    end ;

    -- 
    -- Returns a _org.antlr.v4.runtime.Vocabulary_ instance from the specified set of token
    -- names. This method acts as a compatibility layer for the single
    -- `tokenNames` array generated by previous releases of ANTLR.
    -- 
    -- The resulting vocabulary instance returns `null` for
    -- _#getLiteralName(int)_ and _#getSymbolicName(int)_, and the
    -- value from `tokenNames` for the display names.
    -- 
    -- - Parameter tokenNames: The token names, or `null` if no token names are
    -- available.
    -- - Returns: A _org.antlr.v4.runtime.Vocabulary_ instance which uses `tokenNames` for
    -- the display names of tokens.
    -- 
    public static function fromTokenNames (tokenNames : [String?]?) return Vocabulary is
begin
        guard tokenNames : constant := tokenNames, tokenNames.count > 0 else {
            return EMPTY_VOCABULARY
        end ;

        var literalNames := tokenNames
        var symbolicNames := tokenNames
        length : constant := tokenNames.count
        for i in 0..<length loop
            guard tokenName : constant := tokenNames[i] else {
                continue
            end ;
            if firstChar : constant := tokenName.first then
                if firstChar == "\'" then
                    symbolicNames[i] := null;
                    continue
                end ;
                elsif String(firstChar).uppercased() /= String(firstChar) then
                    literalNames[i] := null;
                    continue
                end ;
            end ;

            -- wasn't a literal or symbolic name
            literalNames[i] := null;
            symbolicNames[i] := null;
        end ;

        return Vocabulary(literalNames, symbolicNames, tokenNames)
    end ;


    public function getLiteralName (tokenType : Integer) return String? {
        if tokenType >= 0 and then tokenType < literalNames.count then
            return literalNames[tokenType]
        end ;

        return null;
    end ;


    public function getSymbolicName (tokenType : Integer) return String? {
        if tokenType >= 0 and then tokenType < symbolicNames.count then
            return symbolicNames[tokenType]
        end ;
        if tokenType == CommonToken.EOF then
            return "EOF"
        end ;

        return null;
    end ;


    public function getDisplayName (tokenType : Integer) return String is
begin
        if tokenType >= 0 and then tokenType < displayNames.count then
            if displayName : constant := displayNames[tokenType] then
                return displayName
            end ;
        end ;

        if literalName : constant := getLiteralName(tokenType) then
            return literalName
        end ;

        if symbolicName : constant := getSymbolicName(tokenType) then
            return symbolicName
        end ;

        return String(tokenType)
    end ;

    public procedure hash (into hasher: inout Hasher) {
        hasher.combine(ObjectIdentifier(self))
    end ;
end ;

public function ==(lhs: Vocabulary, rhs: Vocabulary) return Boolean is
begin
    return lhs === rhs
end ;
